# Generated by Django 4.2.3 on 2023-08-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_sellerrequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='approved',
        ),
    ]
