# Generated by Django 4.2.3 on 2023-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_userprofile_profile_image_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSpecialOffer',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='special_offer_images/')),
            ],
        ),
    ]
