# Generated by Django 4.2.3 on 2023-08-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0007_homespecialoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categ_id', models.AutoField(primary_key=True, serialize=False)),
                ('categ_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_cat_name', models.CharField(max_length=255)),
                ('categ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('sub_categ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.productsubcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
