# Generated by Django 4.2.3 on 2023-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_productcategory_productsubcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='categ_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductSubcategory',
        ),
    ]
