# Generated by Django 4.2.3 on 2023-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_product_productcategory_productsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='categ_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
