# Generated by Django 4.2.3 on 2023-09-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_productcategory_categ_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
