# Generated by Django 4.2.3 on 2023-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='instructions',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
