# Generated by Django 4.2.3 on 2023-09-07 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_productdescription_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
