# Generated by Django 4.2.3 on 2023-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_sellerrequest_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrequest',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
