# Generated by Django 4.2.3 on 2023-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_alter_sellerrequest_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='categ_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
