# Generated by Django 4.2.3 on 2023-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_alter_productcategory_categ_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='sub_cat_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
