# Generated by Django 4.2.3 on 2023-09-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_alter_product_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.product', unique=True),
        ),
    ]
