# Generated by Django 4.2.3 on 2023-09-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_alter_productdescription_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='prod_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Website.product'),
        ),
    ]
