# Generated by Django 4.2.3 on 2023-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0029_addcart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
