# Generated by Django 4.2.3 on 2023-09-17 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0033_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
