# Generated by Django 4.2.3 on 2023-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0034_sellerrequest_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='subcat_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
