# Generated by Django 4.2.5 on 2023-09-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0036_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
