# Generated by Django 4.2.5 on 2023-09-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0038_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='prod_id',
            new_name='prod',
        ),
    ]
