# Generated by Django 4.2.5 on 2023-09-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0041_productrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='category',
            new_name='categ_id',
        ),
    ]
