# Generated by Django 4.2.5 on 2023-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0042_rename_category_productrequest_categ_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='outof_rating',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
