# Generated by Django 4.2.5 on 2023-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0044_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('fish_id', models.AutoField(primary_key=True, serialize=False)),
                ('fish_name', models.CharField(max_length=255)),
            ],
        ),
    ]
