# Generated by Django 4.2.5 on 2023-10-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0045_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fish_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Website.fish'),
            preserve_default=False,
        ),
    ]
