# Generated by Django 4.2.6 on 2024-01-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0046_product_fish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10)),
                ('duration', models.DurationField()),
                ('booking_link', models.URLField()),
            ],
        ),
    ]
