# Generated by Django 4.2.6 on 2024-01-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0048_event_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
