# Generated by Django 4.2.6 on 2024-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0053_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
