# Generated by Django 4.2.6 on 2024-01-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0057_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
