# Generated by Django 4.2.6 on 2024-01-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0060_subscription_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_details',
            name='sub_image',
            field=models.CharField(max_length=255),
        ),
    ]
