# Generated by Django 4.2.6 on 2024-01-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0061_alter_subscription_details_sub_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription_details',
        ),
    ]
