# Generated by Django 4.2.6 on 2024-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0063_subscription_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
