# Generated by Django 4.2.6 on 2024-01-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0064_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
