# Generated by Django 4.2.6 on 2024-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0067_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
