# Generated by Django 4.2.6 on 2024-01-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0068_communitypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='likes',
        ),
    ]
