# Generated by Django 4.2.6 on 2024-01-30 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0069_remove_communitypost_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.communitypost')),
            ],
            options={
                'unique_together': {('post_id', 'liked_user')},
            },
        ),
    ]
