# Generated by Django 4.2.6 on 2024-01-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0070_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='likes',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
