# Generated by Django 4.2.6 on 2024-01-30 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0071_remove_postlikes_likes_communitypost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
