# Generated by Django 4.2.6 on 2024-02-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0072_postlikes_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
