# Generated by Django 4.2.6 on 2024-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0073_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
