# Generated by Django 4.2.6 on 2024-02-20 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0075_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification_Seller',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('seller_name', models.CharField(max_length=100)),
                ('noti_date', models.DateField(auto_now_add=True)),
                ('shipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
