# Generated by Django 4.2.6 on 2024-02-20 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0076_ordernotification_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernotification_seller',
            name='user',
        ),
        migrations.AlterField(
            model_name='ordernotification_seller',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
