# Generated by Django 4.2.6 on 2024-02-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0077_remove_ordernotification_seller_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fish_name',
        ),
    ]
