# Generated by Django 4.2.6 on 2024-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0078_remove_product_fish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='house_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
