# Generated by Django 4.2.6 on 2024-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0080_alter_ordernotification_seller_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification_seller',
            name='hub',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
