# Generated by Django 4.2.6 on 2024-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0081_ordernotification_seller_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification_seller',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
