# Generated by Django 4.2.6 on 2024-02-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0084_userprofile_hub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification_seller',
            name='main_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.order'),
        ),
    ]
