# Generated by Django 4.2.6 on 2024-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0085_ordernotification_seller_main_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_received',
            field=models.BooleanField(default=False),
        ),
    ]
