# Generated by Django 4.2.6 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0087_ordernotification_seller_stored_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
