# Generated by Django 4.2.6 on 2024-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0088_subscription_status_alter_subscription_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification_seller',
            name='prod_cat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
